Repository tulsaschoolsdata/courses, pull requests merged in 2022-11, with the labels that each got.

#11 EditorConfig and Strict Node engine
  .editorconfig
  .node-version
  .npmrc
Labels: size/S

#12 next export now successfully builds
  components/card.js
  pages/course/[cid].js
  pages/index.js
Labels: size/L, needs-review

#14 Adds formkit's AutoAnimate lib for easily adding animation effects to elements
  package-lock.json
  package.json
  pages/index.js
Labels: size/XS, needs-review

#13 addresses github action CI error - engine not compatible
  package-lock.json
  package.json
Labels: bug, size/XS

#16 adds next/router
  components/card.js
  pages/course/[cid].js
Labels: size/S

#25 add: course catalog builder
  data/.gitignore
  data/generators/.env.sample
  data/generators/.ruby-version
  data/generators/catalog
  data/generators/lib/power_school.rb
  data/generators/lib/power_school/client.rb
  data/generators/lib/power_school/power_query.rb
Labels: size/L, needs-review

#32 Desktop View: UI Improvements
  components/card.js
  components/layout.js
  components/page-container.js
  lib/filters.js
  pages/index.js
Labels: size/L

#23 adds ruby github action
  .github/workflows/deploy.yml
Labels: size/XS

#39 Modify Page Head
  pages/_app.js
  pages/course/[id].js
Labels: size/M
